---
# tasks file for logstash-role

- include: logstash_requirements.yml
  tags:
   - logstash_req

- name: Stop Logstash before upgrading
  service: name=logstash
           state=stopped
  ignore_errors: yes

- include: logstash_installation_Debian.yml
  when: ansible_os_family == "Debian"

- include: logstash_installation_RedHat.yml
  when: ansible_os_family == "RedHat"

- include: logstash_configuration.yml
  tags:
   - logstash_conf

- name: Start Logstash
  service: name=logstash
           state=started
           enabled=yes
