---
- include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_os_family }}.yml"

- include: conf.yml

- include: haproxy.yml
  when: haproxy_script_location != ""

- name: Start Marathon service
  service: name=marathon state=restarted enabled=yes 
