- hosts: "tag_Type_mesos:&tag_Cluster_{{ cluster_prefix }}"
  vars_files:
    - "vars/{{ varfile }}"
  become: true

  tasks:
    - name: Upgrade all packages in RedHat-based machines
      when: ansible_os_family == "RedHat"
      yum: name=* state=latest
