- name: Identify master node(s), update name and tag with Role=master
  hosts: "tag_Type_mesos:&tag_Cluster_{{ ec2_tag_Cluster }}:&tag_Role_master"
  become: yes
  vars_files:
    - "vars/{{ varfile }}"
  tasks:

  - add_host: name="{{ item.1 }}" groups=mesos_masters,zookeeper_hosts zoo_id="{{ item.0 }}"
    with_indexed_items: "{{ play_hosts }}"
    tags: always

- name: Create deployment artifacts
  hosts: localhost
  connection: local
  vars_files:
    - "vars/{{ varfile }}"
  vars:
    - zookeeper_hostnames: "{% for host in groups['zookeeper_hosts'] %}{{ hostvars[host].ec2_private_ip_address }}:2181{% if not loop.last %},{% endif %}{% endfor %}"
  tasks:

    - name: Create temp deploy directory
      file: path="{{ deploy_home }}" state=directory

    - name: Install marathon infrastructure launch script
      template: src=../files/infrastructure.json.j2 dest={{ deploy_home }}/infrastructure.json mode=400

    - name: Install marathon demo launch script
      template: src=../files/demo.json.j2 dest={{ deploy_home }}/demo.json mode=400

    - name: Install bookmarks listing
      template: src=../files/cluster-bookmarks.txt.j2 dest={{ deploy_home }}/cluster-bookmarks.txt mode=400

    - name: Install marathon launcher helper script
      copy: src=../files/marathon.sh dest={{ deploy_home }}/marathon.sh mode=0500
