#
# Prepare systems for configuration
#
- name: Prepare systems for configuration
- hosts: "tag_type-mesos:&tag_cluster-{{ cluster_prefix }}"
  become: yes
  vars_files:
    - "vars/{{ varfile }}"
  tasks:

  - name: Remove require tty
    lineinfile: regexp="Defaults\s+requiretty" dest=/etc/sudoers state=absent
