- name: Install autofs package
  yum: name=autofs

- name: Install autofs /etc/sysconfig file
  template: src=autofs.j2 dest=/etc/sysconfig/autofs mode=0644
  notify:
    - retart autofs

- name: Install auto.master /etc config file
  template: src=auto.master.j2 dest=/etc/auto.master mode=0644
  notify:
    - retart autofs

- name: Install auto.direct /etc config file
  template: src=auto.direct.j2 dest=/etc/auto.direct mode=0644
  notify:
    - retart autofs

- name: Create mount directory if specified
  file: path="{{ gluster_mount_dir }}" state=directory
  when: gluster_mount_dir is defined

- name: Ensure autofs is running
  service: name=autofs state=started enabled=yes
