---

- hosts: localhost
  connection: local
  sudo: yes
  gather_facts: false
  
  tasks:
    - wait_for: port=2181 state=started delay=1
    
    - shell: echo stat | nc 127.0.0.1 2181
      register: status
      failed_when: status.rc != 0
