# Package repos
mesosphere_yum_repo: "http://repos.mesosphere.com/el/{{ ansible_distribution_major_version }}/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm"
epel_repo: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"

# Kernel update can trigger an auto reboot if allowed
auto_reboot_allowed: false

# Tool versions used when downloading packages
mesos_version: "0.28"
marathon_version: "15.3"
java_version: "8"

# Mesos cluster config defaults
mesos_cluster_name: "dev-cluster"
mesos_containerizers: "docker,mesos"
mesos_master_count: 1

# Mesos DNS defaults
external_dns_resolver: "\"8.8.8.8\", \"8.8.4.4\""

# Location of the marathon launch helper script
marathon_launch_config_home: /home/centos

# Elasticsearch used for logs defaults
elasticsearch_cluster_name: DemoCluster

# Gluster file system mount information (optional)
gluster_mount_dir: /mnt
gluster_mount_info: ""

# The directory into which the service credentials and Marathon launch JSON file will be written
deploy_home: deploy
