---
- include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_os_family }}.yml"

- include: conf.yml

- include: haproxy.yml
  when: haproxy_script_location != ""

- name: Delete old slave info to ensure clean startup of Chronos after an upgrade
  file: path=/tmp/mesos/meta/slaves/latest state=absent

